name: Update Project Tree

on:
  schedule:
    # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:
    # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Generate and update README
      run: 
        tree=$(find . -type d -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g')
        start='<!--START_SECTION:tree-->'
        end='<!--END_SECTION:tree-->'
        replacement="$start\n\`\`\`\n$tree\n\`\`\`\n$end"
        sed -i "/^$start$/,/^$end$/c\\$replacement" README.md

    - name: Commit and push if changes
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update README with directory structure" || exit 0
        git push
